[package]
name = "cargo_janitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3"
syn = { version = "2.0", features = ["full", "visit"] }
toml = "0.7"
