[package]
name = "other_package_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
package_1 = { path = "../../workspace_1/lib/package_1" }
